/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.jiat.neolibrary.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import lk.jiat.neolibrary.component.RoundButton;
import lk.jiat.neolibrary.dialog.Login;
import lk.jiat.neolibrary.dialog.Register;

/**
 *
 * @author Yashitha
 */
public class SelectScreen extends javax.swing.JFrame {

    /**
     * Creates new form SelectScreen
     */
    
    public SelectScreen() {
        FlatDarkLaf.setup();
        initComponents();
        init();
    }
    
    private void init() {
        // Set up the logo
        FlatSVGIcon icon = new FlatSVGIcon("lk/jiat/neolibrary/images/logo.svg", 120, 120);
        logo.setIcon(icon);
        
        // Set up the title
        titleLabel.setText("Z Library");
        titleLabel.setFont(new Font("Inter", Font.BOLD, 36));
        titleLabel.setForeground(new Color(255, 255, 255));
        
        // Set up the subtitle
        subtitleLabel.setText("Welcome to the future of library management");
        subtitleLabel.setFont(new Font("Inter", Font.PLAIN, 16));
        subtitleLabel.setForeground(new Color(200, 200, 200));
        
        // Style the buttons
        styleButton((RoundButton) loginBtn, "LOGIN", new Color(99, 102, 241));
        styleButton((RoundButton) registerBtn, "REGISTER", new Color(34, 197, 94));
        
        // Set up the glassmorphism panel
        glassPanel.setOpaque(false);
        glassPanel.setBorder(BorderFactory.createEmptyBorder(40, 40, 40, 40));
    }
    
    private void styleButton(RoundButton button, String text, Color color) {
        button.setText(text);
        button.setFont(new Font("Inter", Font.BOLD, 16));
        button.setPreferredSize(new java.awt.Dimension(280, 55));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        // Remove any hardcoded colors - let RoundButton handle styling
        button.setBackground(null);
        button.setForeground(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new GradientPanel();
        glassPanel = new GlassPanel();
        logo = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        loginBtn = new RoundButton();
        registerBtn = new RoundButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainPanel.setLayout(new java.awt.BorderLayout());

        glassPanel.setLayout(new java.awt.BorderLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setPreferredSize(new java.awt.Dimension(120, 120));

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Z Library");

        subtitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitleLabel.setText("Welcome to the future of library management");

        loginBtn.setText("LOGIN");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setPreferredSize(new java.awt.Dimension(280, 55));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        registerBtn.setText("REGISTER");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.setPreferredSize(new java.awt.Dimension(280, 55));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glassPanelLayout = new javax.swing.GroupLayout(glassPanel);
        glassPanel.setLayout(glassPanelLayout);
        glassPanelLayout.setHorizontalGroup(
            glassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glassPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(glassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        glassPanelLayout.setVerticalGroup(
            glassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glassPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        mainPanel.add(glassPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        Login loginDialog = new Login(this, true);
        loginDialog.setLocationRelativeTo(this);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        Register registerDialog = new Register(this, true);
        registerDialog.setLocationRelativeTo(this);
        registerDialog.setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    // Custom gradient background panel
    private static class GradientPanel extends JPanel {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g.create();
            g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            
            // Create gradient background with more visible colors
            GradientPaint gradient = new GradientPaint(
                0, 0, new Color(17, 24, 39),  // Dark blue-gray
                getWidth(), getHeight(), new Color(55, 65, 81)  // Lighter blue-gray
            );
            g2d.setPaint(gradient);
            g2d.fillRect(0, 0, getWidth(), getHeight());
            
            g2d.dispose();
        }
    }
    
    // Custom glassmorphism panel
    private static class GlassPanel extends JPanel {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g.create();
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            
            // Create glassmorphism effect with more visible transparency
            g2d.setColor(new Color(255, 255, 255, 30));
            g2d.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
            
            // Add subtle border
            g2d.setColor(new Color(255, 255, 255, 50));
            g2d.setStroke(new java.awt.BasicStroke(1));
            g2d.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            
            g2d.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel glassPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
